name: PullRequestCheck

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4

      # https://github.com/actions/setup-java
      - name: set up JDK 11
        uses: actions/setup-java@4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build
