name: PullRequestCheck

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-java
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # https://qiita.com/sudo5in5k/items/5b6da5dbba3fc2514319
      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json

      # https://developer.android.com/studio/test/command-line
      - name: Run local unit tests
        run: ./gradlew test

  # https://github.com/ScaCap/action-ktlint
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

  # https://github.com/yutailang0119/action-android-lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - name: copy google-service
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
        run: echo $GOOGLE_SERVICE | base64 --decode --ignore-garbage > ./app/google-services.json
      - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v4
        with:
          report-path: build/reports/*.xml
          ignore-warnings: true
        continue-on-error: false
